### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by feculay** [def670/ethoclub#2]
Hola ,tuve un error al configurar eth.coinbase a un monedero externo y unlock payment a un monedero local, el problema es que el bloque minado figura con el saldo pero no puedo disponer de esas monedas, cómo.podria.solucionar este tema?. Gracias

**Comment by def670** [comment]
lo siento no hablo español tu hablas ingles?

**Comment by def670** [comment]
coloque su archivo de almacén de claves en .ether1/keystore/ para ambas cuentas y luego debería poder acceder a ambas. es posible que deba usar geth added para desbloquear las cuentas... avíseme si necesita ayuda con eso

**Comment by feculay** [comment]
muchas gracias por contestar, el problema es el siguiente:
1:como unlock wallet coloque wallet local que poseo la llave.
2: por error coloque en payouts coloque wallet de coinbase, en vez de igualar a llave unlock, mine un bloque etc, en explorer figura ese saldo por minar el bloque , pero en coinbase no aparece, ahi viene mi problema

Thank you very much for answering, the problem is as follows: 1: how to unlock wallet place local wallet that I have the key. 2: by mistake I put in payouts I put a coinbase wallet, instead of equaling the unlock key, mine a block etc, in explorer that balance appears for mining the block, but in coinbase it does not appear, here comes my problem

https://expedition.dev/block/0x775ffd90b2be37af72fce303cc9289155cc91f679636d4f2acc39c1cfb8c49df
wallet coinbase : [0x898e3115913a4124a1d299fdb02bfa44647d5e09](https://expedition.dev/address/0x898e3115913a4124a1d299fdb02bfa44647d5e09)
gracias por su ayuda

**Comment by def670** [comment]
vea si su billetera coinbase admite esa moneda. si no, intente acceder a esa dirección con metamask. lo siento, nunca usé coinbase antes.

see if your coinbase wallet supports that coin.  if not then try to access that address with metamask.  sorry i never used coinbase before.

Don   

    On Monday, August 15, 2022 at 09:50:32 a.m. EDT, feculay ***@***.***> wrote:  
 
 


muchas gracias por contestar, el problema es el siguiente:
1:como unlock wallet coloque wallet local que poseo la llave.
2: por error coloque en payouts coloque wallet de coinbase, en vez de igualar a llave unlock, mine un bloque etc, en explorer figura ese saldo por minar el bloque , pero en coinbase no aparece, ahi viene mi problema

Thank you very much for answering, the problem is as follows: 1: how to unlock wallet place local wallet that I have the key. 2: by mistake I put in payouts I put a coinbase wallet, instead of equaling the unlock key, mine a block etc, in explorer that balance appears for mining the block, but in coinbase it does not appear, here comes my problem

https://expedition.dev/block/0x775ffd90b2be37af72fce303cc9289155cc91f679636d4f2acc39c1cfb8c49df
wallet coinbase : 0x898e3115913a4124a1d299fdb02bfa44647d5e09
gracias por su ayuda
